#ifndef __PHYSICSTYPES_H__
#define __PHYSICSTYPES_H__

typedef enum ba_physics_type_e {
    BA_PHYSICS_0_NONE,
    BA_PHYSICS_1_UNKNOWN,
    BA_PHYSICS_2_NORMAL,
    BA_PHYSICS_3_LOCKED_ROTATION,
    BA_PHYSICS_4_UNKNOWN,
    BA_PHYSICS_5_INVERTED_YAW,
    BA_PHYSICS_6_AIRBORN,
    BA_PHYSICS_7_FREEZE,
    BA_PHYSICS_8_UNKNOWN,
    BA_PHYSICS_9_NO_GRAVITY,
    BA_PHYSICS_A_CLIMB,
    BA_PHYSICS_B_TRANSFORM,
    BA_PHYSICS_C_GOTO,
    BA_PHYSICS_D_END,
    BA_PHYSICS_E_UNKNOWN
} BaPhysicsType;

#endif